services:
  auth-db:
    image: mongo:8.0.3
    container_name: auth-db
    env_file:
      - .env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh
      interval: 5s
      timeout: 5s
      retries: 5
    attach: false
    networks:
      - internal

  auth-backend:
    build: .
    container_name: auth-backend
    depends_on:
      auth-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8080:3000'
    networks:
      - internal

networks:
  internal:
    driver: bridge
